---
title: "Pub Bias"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(countreg)
library(pscl)
library(colorspace)
library(ggplot2)
```

## Hurdle Model

```{r}
Gini<-pubda$GINI.index..World.Bank.estimate.
Education<-pubda$Educational.attainment..at.least.completed.post.secondary..population.25...total......cumulative.
Research<-pubda$Research.and.development.expenditure....of.GDP.
GDP<-pubda$GDP..constant.2010.US..
logGDP <- log(GDP)

AR1nb<-hurdle(authorRepresentation ~ AvTD + log(GDP) + 
                Gini + 
                Education +
                Research, 
              dist = "negbin", zero.dist = "binomial", data = pubda)

AR1poisson<-hurdle(authorRepresentation ~ AvTD + log(GDP) + 
                Gini + 
                Education +
                Research, 
              dist = "poisson", zero.dist = "binomial", data = pubda)

AIC(AR1nb)
AIC(AR1poisson)
```

```{r}
summary(AR1nb)
```

```{r}
qqrplot(AR1nb)
rootogram(AR1nb)
```

```{r}
AR2<-hurdle(authorRepresentation ~ log(GDP) + Gini +
                Education + Research | 
                AvTD + log(GDP) + Gini + Education, 
              dist = "negbin", data = pubda)
AIC(AR1nb, AR2)

library(jtools)
tab_model(
  AR1nb, 
  dv.labels = c("Author representation"),
  string.p = "P-value", 
  file = "AR-model.doc"
)
```

```{r}
collab1<-hurdle(collab ~ AvTD + log(GDP) + 
                Gini + 
                Education +
                Research, 
              dist = "negbin", data = pubda)

collab1poisson<-hurdle(collab ~ AvTD + log(GDP) + 
                Gini + 
                Education +
                Research, 
              dist = "poisson", data = pubda)
AIC(collab1, collab1poisson)

summary(collab1)

collab2<-hurdle(collab ~ log(GDP) + Gini + Education + Research | AvTD + log(GDP) + Education + Research, dist = "negbin", data = pubda)
AIC(collab1, collab2)

qqrplot(collab1)
rootogram(collab1)

tab_model(
  collab1, 
  dv.labels = c("Author collaborations"),
  string.p = "P-value", 
  file = "collab-model.doc"
)
```

```{r}
mismatch1<-hurdle(allMismatch ~ AvTD + log(GDP) + 
                Gini + 
                Education +
                Research, 
              dist = "negbin", data = pubda)

mismatch1poisson<-hurdle(allMismatch ~ AvTD + log(GDP) + 
                Gini + 
                Education +
                Research, 
              dist = "poisson", data = pubda)
AIC(mismatch1, mismatch1poisson)

mismatch2<-hurdle(allMismatch ~ log(GDP) + Gini + Education + Research | AvTD + log(GDP) + Gini + Research, dist = "poisson", data = pubda)
AIC(mismatch1, mismatch2)

qqrplot(mismatch1)
rootogram(mismatch1)

tab_model(
  mismatch1, 
  dv.labels = c("Author mismatches"),
  string.p = "P-value", 
  file = "mismatch-model.doc"
)
```

## Graphs:

```{r}
library(gridExtra)
library(ggpubr)

#author representation 

p1 <- ggplot(pubda, aes(x=logGDP, y = authorRepresentation, color = AvTD)) + 
  geom_point() +
  theme_gray() +
  labs(x="Log Average GDP (1980-2019)", y = "AR") +
  scale_colour_continuous_sequential(palette = "Lajolla", trans = "reverse", na.value = "black") + 
  geom_smooth(method=lm, color = "darkgoldenrod") +
  geom_text(aes(label=ifelse(authorRepresentation>430,as.character(country),'')),hjust=1,vjust=1)

p2 <- ggplot(pubda, aes(x=AvTD, y = authorRepresentation, color = logGDP)) + 
  geom_point() +
  theme_dark() +
  labs(x="Average taxonomic distinctiveness", y = "AR") +
  scale_colour_continuous_sequential(palette = "Dark Mint", na.value = "black") +
  geom_text(aes(label=ifelse(authorRepresentation>430,as.character(country),'')),hjust=1,vjust=1)

ar_plot <- ggarrange(p1, p2, 
          labels = c("A", "B"),
          ncol = 1, nrow = 2)

ar_plot <- annotate_figure(ar_plot,
                top = text_grob("Author representation", face = "bold", size = 14))

ar_plot

ggsave(
  "ar-plot.tiff",
  plot = last_plot(),
  scale = 1.5,
  dpi = 300,
  limitsize = TRUE,
)

#collaborations

p3 <- ggplot(pubda, aes(x=logGDP, y = collab, color = AvTD)) + 
  geom_point() +
  theme_gray() +
  labs(x="Log average GDP (1980-2019)", y = "Collab.") +
  scale_colour_continuous_sequential(palette = "Lajolla", na.value = "black") + 
  geom_smooth(method=lm, color = "darkgoldenrod") + 
  geom_text(aes(label=ifelse(collab>39,as.character(country),'')),hjust=1,vjust=1)

p4 <- ggplot(pubda, aes(x=AvTD, y = collab, color = logGDP)) + 
  geom_point() +
  theme_dark() +
  labs(x="Average taxonomic distinctiveness", y = "Collab.") +
  scale_colour_continuous_sequential(palette = "Dark Mint", na.value = "black") + 
  geom_text(aes(label=ifelse(collab>39,as.character(country),'')),hjust=1,vjust=1)

c_plot <- ggarrange(p3, p4, 
          labels = c("A", "B"),
          ncol = 1, nrow = 2)

c_plot <- annotate_figure(c_plot,
                top = text_grob("Collaborations", face = "bold", size = 14))

c_plot

ggsave(
  "c-plot.tiff",
  plot = last_plot(),
  scale = 1.5,
  dpi = 300,
  limitsize = TRUE,
)


#mismatches
p5 <- ggplot(pubda, aes(x=logGDP, y = allMismatch, color = AvTD)) + 
  geom_point() +
  theme_gray() +
  labs(x="Log average GDP (1980-2019)", y = "Mismatches") +
  scale_colour_continuous_sequential(palette = "Lajolla", trans = "reverse", na.value = "black") + 
  geom_smooth(method=lm, color = "darkgoldenrod") + 
  geom_text(aes(label=ifelse(allMismatch>45,as.character(country),'')),hjust=1,vjust=1)

p6 <- ggplot(pubda, aes(x=AvTD, y = allMismatch, color = logGDP)) + 
  geom_point() +
  theme_dark() +
  labs(x="Average taxonomic distinctiveness", y = "Mismatches") +
  scale_colour_continuous_sequential(palette = "Dark Mint", na.value = "black") + 
  geom_text(aes(label=ifelse(allMismatch>45,as.character(country),'')),hjust=1,vjust=1)

m_plot <- ggarrange(p5, p6, 
          labels = c("A", "B"),
          ncol = 1, nrow = 2)

m_plot <- annotate_figure(m_plot,
                top = text_grob("Author-species mismatches", face = "bold", size = 14))

m_plot

ggsave(
  "m-plot.tiff",
  plot = last_plot(),
  scale = 1.5,
  dpi = 300,
  limitsize = TRUE,
)
```
